DESPERATE_ATTACK_WITHOUT_ORG_WHEN_NO_ORG_GAIN = 120,
MAX_REQUEST_EXPEDITIONARIES_ARMY_RATIO = 0.2,
CASUALTY_RATIO_TO_PULL_EXPEDITIONARIES_BACK = 0.1,
CASUALTY_RATIO_TO_NOT_SEND_EXPEDITIONARIES = 0.05,